version: '3'

services:
  api:
    build: ./server
    volumes:
      - ./server:/app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./server/.env
  
  client:
    build: ./client
    command: sh -c "serve -s build"
    env_file:
      - ./client/.env
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - client